export const ruuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/; // eslint-disable-line
export const rgender = /^(m|f)$/; // eslint-disable-line
export const rgendern = /^(m|f|n)$/; // eslint-disable-line
export const rcommitmentperiodenum = /^(cannotcommit|lessthanonemonth|morethanonemonth|morethanthreemonths|morethansixmonths|morethanoneyear)$/; // eslint-disable-line
export const rrecurrence = /^(n|w|f)$/; // eslint-disable-line
export const rfrequency = /^(w|f|m)$/; // eslint-disable-line
export const rcontact = /^(m|e)$/; // eslint-disable-line
export const rpaymentmethod = /^(directDebit|bankTransfer)$/; // eslint-disable-line
export const rdate = /^\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])$/; // eslint-disable-line
export const rtime = /^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)$/; // eslint-disable-line
export const rdecimal = /^(\d*\.)?\d+$/;
export const rdatetime = /^\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01]) (?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)$/;
export const rexpectedtoliveinaustraliaperiod = /^(onetosixmonths|sixtotwelvemonths|twelvetotwentyfourmonths|longetthantwentyfourmonths)$/; // eslint-disable-line
export const rworkinghoursperweekideally = /^(onetofourhoursperweek|fivetotenhoursperweek|eleventofifteenhoursperweek|sixteentotwentyhoursperweek|twentyonetothirtyhoursperweek|thirtyonetofourtyhoursperweek)$/; // eslint-disable-line
export const rhowlongwouldbutlerworkwithus = /^(underonemonth|onetotwomonths|threetosixmonths|sixtoninemonths|ninetotwelvemonths|twelvetotwentyfourmonths|morethantwentyfourmonths|untilifindanotherjob|untilschoolstarts)$/; // eslint-disable-line
export const rbsbexactlength = /^\w{6}$/;
export const rpotentialreasonsbutlerwillleaveus = /^(nonesincebutlerwillworkforatleastsixmonths|yessincestudycommitmentswillincrease|yessincemightfindanotherjob|yessincebutlerwillbeleavethecountry|yessincebutlerwillhavefamilycommitments|yesbutlerwillhavetoleaveforanotherreason)$/; // eslint-disable-line
export const rreferencecheck = /^(successful|unsuccessful|incomplete)$/; //eslint-disable-line
export const renglishcheck = /^(advanced|intermediate|beginner|incomplete)$/; // eslint-disable-line
export const ronboardedontoplatform = /^(yes|incomplete)$/; // eslint-disable-line
export const rbutlernoshowreason = /^(personalmedicalemergency|operatorerror|didnotcheckscheduleunawareofallocation|personalscheduleclash|workscheduleclash|transportissues|refusingtovisitegpaydispute|noresponse|otherreason)$/; //eslint-disable-line
export const rbutlerunchurnattempted = /^(yes|no|notattempted)$/; //eslint-disable-line
export const rfeedbackappealedstatus = /^(appealed|appealresolved|noappeal)$/; //eslint-disable-line
export const rreschedulestatus = /^(successfullyrescheduled|churned|notcontacted)$/;
export const rbutlerAllocatedByMethod = /^(manual|managedschedulesystem|butlerrequestedthisvisit|trs)$/;
